data = [{"id": 1, "first_name": "Gannie", "last_name": "Gabbitas", "email": "ggabbitas0@weebly.com", "gender": "M", "movie_gen": "Comedy|Drama|Fantasy|Romance"},
        {"id": 2, "first_name": "Richardo", "last_name": "Pilling",
         "email": "rpilling1@acquirethisname.com", "gender": "M", "movie_gen": "Action"},
        {"id": 3, "first_name": "Garret", "last_name": "Porter",
         "email": "gporter2@sfgate.com", "gender": "M", "movie_gen": "Drama"},
        {"id": 4, "first_name": "Cloe", "last_name": "Spenton",
         "email": "cspenton3@sfgate.com", "gender": "F", "movie_gen": "Action"},
        {"id": 5, "first_name": "Albertina", "last_name": "Really",
         "email": "areally4@discovery.com", "gender": "F", "movie_gen": "Comedy|Drama|Romance"},
        {"id": 6, "first_name": "Penny", "last_name": "Juleff",
         "email": "pjuleff5@walmart.com", "gender": "M", "movie_gen": "Comedy"},
        {"id": 7, "first_name": "Eleanora", "last_name": "Tetlow",
         "email": "etetlow6@slate.com", "gender": "F", "movie_gen": "Children|Comedy"},
        {"id": 8, "first_name": "Gareth", "last_name": "Jellybrand",
         "email": "gjellybrand7@psu.edu", "gender": "M", "movie_gen": "Comedy"},
        {"id": 9, "first_name": "Cathryn", "last_name": "Abramowitz",
         "email": "cabramowitz8@go.com", "gender": "F", "movie_gen": "Drama"},
        {"id": 10, "first_name": "Konstantin", "last_name": "Davet",
         "email": "kdavet9@discovery.com", "gender": "M", "movie_gen": "Action|Drama|Romance"},
        {"id": 11, "first_name": "Stillmann", "last_name": "Smidmore",
         "email": "ssmidmorea@hexun.com", "gender": "M", "movie_gen": "Horror|Sci-Fi"},
        {"id": 12, "first_name": "Matty", "last_name": "McIlrath",
         "email": "mmcilrathb@tamu.edu", "gender": "M", "movie_gen": "Thriller"},
        {"id": 13, "first_name": "Fredric", "last_name": "Spaducci",
         "email": "fspaduccic@about.com", "gender": "M", "movie_gen": "Action|Horror"},
        {"id": 14, "first_name": "Anya", "last_name": "Comberbach",
         "email": "acomberbachd@ifeng.com", "gender": "F", "movie_gen": "Comedy|Drama"},
        {"id": 15, "first_name": "Rubetta", "last_name": "Pietzker", "email": "rpietzkere@globo.com",
         "gender": "F", "movie_gen": "Adventure|Animation|Children|Comedy"},
        {"id": 16, "first_name": "Tiebold", "last_name": "Geibel",
         "email": "tgeibelf@printfriendly.com", "gender": "M", "movie_gen": "Drama|Film-Noir|Thriller"},
        {"id": 17, "first_name": "Angus", "last_name": "Jenkins",
         "email": "ajenkinsg@netvibes.com", "gender": "M", "movie_gen": "Crime|Mystery"},
        {"id": 18, "first_name": "Cassaundra", "last_name": "Moreinis",
         "email": "cmoreinish@sogou.com", "gender": "F", "movie_gen": "Documentary"},
        {"id": 19, "first_name": "Enrique", "last_name": "Rainy",
         "email": "erainyi@dropbox.com", "gender": "M", "movie_gen": "Drama"},
        {"id": 20, "first_name": "Zollie", "last_name": "Bennet", "email": "zbennetj@sogou.com", "gender": "M", "movie_gen": "Documentary"}]
